name: base_flutter_clean_getx_app
description: Base Flutter Clean GetX App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.1.1
  get_it:
  freezed: ^2.3.2
  shared_preferences: ^2.2.0
  permission_handler: ^10.2.0
  dartz: ^0.10.1
  html: ^0.15.0
  http: ^0.13.5
  dio: ^5.3.2
  open_file_plus: ^3.4.1
  flutter_file_dialog: ^3.0.2
  json_annotation: ^4.8.1
  path_provider: ^2.0.12
  url_strategy: ^0.2.0
  intl: ^0.18.1
  timezone: ^0.8.0
  auto_size_text: ^3.0.0
  flutter_animate: ^4.1.0
  loading_animation_widget: ^1.2.0+4
  auto_route: ^7.8.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  build_test: ^2.1.6
  build_web_compilers: ^3.2.7
  responsive_framework: ^0.2.0
  freezed_annotation: ^2.2.0
  json_serializable: ^6.5.4
  flutter_launcher_icons: ^0.13.1
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/fonts/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf